# Generated by Django 6.0.3 on 2026-03-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_otheraccessoriesmodel_jeanmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagpackmodel',
            name='Image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bagpackmodel',
            name='Price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bagpackmodel',
            name='Type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otheraccessoriesmodel',
            name='Image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otheraccessoriesmodel',
            name='Price',
            field=models.CharField(default=11, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otheraccessoriesmodel',
            name='Type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweatermodel',
            name='Image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweatermodel',
            name='Price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweatermodel',
            name='Type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tshirtmodel',
            name='Image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tshirtmodel',
            name='Price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tshirtmodel',
            name='Type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
