# Generated by Django 6.0.3 on 2026-03-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_bagpackmodel_image_bagpackmodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagpackmodel',
            name='Image',
            field=models.ImageField(upload_to='bagpacks/'),
        ),
        migrations.AlterField(
            model_name='jeanmodel',
            name='Image',
            field=models.ImageField(upload_to='jeans/'),
        ),
        migrations.AlterField(
            model_name='otheraccessoriesmodel',
            name='Image',
            field=models.ImageField(upload_to='otheraccessories/'),
        ),
        migrations.AlterField(
            model_name='sweatermodel',
            name='Image',
            field=models.ImageField(upload_to='sweaters/'),
        ),
        migrations.AlterField(
            model_name='tshirtmodel',
            name='Image',
            field=models.ImageField(upload_to='tshirts/'),
        ),
    ]
