# Generated by Django 6.0.2 on 2026-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeansname', models.TextField(max_length=30)),
                ('jeansdescription', models.TextField(max_length=100)),
                ('jeansprice', models.IntegerField(max_length=10)),
                ('jeanstype', models.TextField(max_length=30)),
            ],
        ),
    ]
