# Generated by Django 6.0.2 on 2026-02-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Models_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bagpacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Description', models.TextField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='jackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Description', models.TextField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='otheraccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Description', models.TextField(max_length=100)),
                ('Price', models.IntegerField(max_length=5)),
                ('Type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='sweaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tshirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Description', models.TextField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Type', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='jeans',
            old_name='jeansdescription',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='jeans',
            name='jeansname',
        ),
        migrations.RemoveField(
            model_name='jeans',
            name='jeansprice',
        ),
        migrations.RemoveField(
            model_name='jeans',
            name='jeanstype',
        ),
        migrations.AddField(
            model_name='jeans',
            name='Name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeans',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeans',
            name='Type',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
