# Generated by Django 6.0.2 on 2026-02-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Models_App', '0002_bagpacks_jackets_otheraccessories_sweaters_tshirts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagpacks',
            name='Image',
            field=models.ImageField(default=1, upload_to='Ecommerce_Models_App'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jackets',
            name='Image',
            field=models.ImageField(default=1, upload_to='Ecommerce_Models_App'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeans',
            name='Image',
            field=models.ImageField(default=1, upload_to='Ecommerce_Models_App'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otheraccessories',
            name='Image',
            field=models.ImageField(default=1, upload_to='Ecommerce_Models_App'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweaters',
            name='Image',
            field=models.ImageField(default=1, upload_to='Ecommerce_Models_App'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tshirts',
            name='Image',
            field=models.ImageField(default=1, upload_to='Ecommerce_Models_App'),
            preserve_default=False,
        ),
    ]
