# Generated by Django 6.0.2 on 2026-02-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Models_App', '0003_bagpacks_image_jackets_image_jeans_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheraccessories',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
